from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import stim

Basis = Literal["Z", "X"]


@dataclass(frozen=True)
class SurfaceCodeParams:
    """Parameters for rotated surface-code memory experiment generated by Stim."""
    d: int
    rounds: int
    p: float
    basis: Basis = "Z"

    def validate(self) -> None:
        if self.d < 3 or self.d % 2 == 0:
            raise ValueError("rotated surface code 通常要求 d 为奇数且 >= 3")
        if self.rounds < 1:
            raise ValueError("rounds 必须 >= 1")
        if not (0.0 <= self.p < 1.0):
            raise ValueError("p 必须在 [0, 1) 之间")
        if self.basis not in ("Z", "X"):
            raise ValueError("basis 必须为 'Z' 或 'X'")


def build_surface_code_circuit(params: SurfaceCodeParams) -> stim.Circuit:
    """Build a rotated surface-code memory experiment circuit with TICK/DETECTOR/OBSERVABLE."""
    params.validate()
    name = "surface_code:rotated_memory_z" if params.basis == "Z" else "surface_code:rotated_memory_x"

    # 一个统一的 p 旋钮：映射到 Stim generator 常见噪声入口
    return stim.Circuit.generated(
        name,
        distance=params.d,
        rounds=params.rounds,
        after_clifford_depolarization=params.p,
        before_measure_flip_probability=params.p,
        after_reset_flip_probability=params.p,
    )


def circuit_text(params: SurfaceCodeParams) -> str:
    """Return Stim DSL text."""
    return str(build_surface_code_circuit(params))


def circuit_ascii_diagram(circuit: stim.Circuit) -> str:
    """ASCII timing diagram."""
    return str(circuit.diagram())
